Introduce enrolled_organization_config table and model
Orange-OpenSource/autosleep pull request #267
Opened 2016-12-05 18:27 UTC by pradyutsarma

1. Story details https://www.pivotaltracker.com/story/show/134541301
2. There will be some refactoring to the model with the REST APIs PR and the transient mode support

2016-12-14 17:06 UTC, gberche-orange commented
thanks @pradyutsarma for this PR. Sorry again for the slow merge. I hope to find time to review in details and merge soon.

2016-12-14 17:32 UTC, pradyutsarma commented
No problem @gberche-orange . I understand.

2016-12-15 13:53 UTC, gberche-orange requested changes
Thanks for this contrib. We do need some changes. 

See some proposals related to these changes at https://github.com/orange-cloudfoundry/autosleep/tree/feature_org_config_db_GB_refinements 

Feel free to cherry pick if this makes sense and update the PR.

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +    }
I think this rather fits in the model than the config class which aims at providing environment variables configs.

See examples in https://github.com/orange-cloudfoundry/autosleep/blob/b9bb86477614b8de94d34742163dada3f3146ea6/common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/ApplicationInfo.java#L205-L205

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +    private Pattern excludeFromAutoEnrollment;
Please consider reusing story/design doc field description as comment ``regex to exclude spaces in this org from autosleep enrollment`` or rename the field to express the intention to exclude **some spaces** from autoenrollment

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +    private String organizationId;
naming: org *guid* feels more in sync with [CC API](http://apidocs.cloudfoundry.org/249/organizations/get_organization_summary.html) (rather than org *id*) reducing confusion

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +            backoffice_enrolled, backoffice_opted_out
Missing the auto_enrolled value documented in https://docs.google.com/document/d/1ZUfs2Okv3Lb4vFpUB0XbRAbKxWhYylNVycKLk2-kB9E/edit#bookmark=id.9a2wsq2xyrtm

``state= auto_enrolled | backoffice_enrolled | backoffice_opted_out``

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +
We might need another excludeAppsFromAutoEnrollement field. Could be added later though.

2016-12-15 13:53 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +public class EnrolledOrganizationConfig {
Naming: this may also represent orgs that are opted out, and not only enrolled orgs, preferring OrgEnrollmentConfig. Any better suggestion ?

2016-12-15 14:08 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +            backoffice_enrolled, backoffice_opted_out
Good point. Missed that. But a question again here: This table anyways captures the configuration for orgs via back office APIs which can be either enrolled or opted-out. How different is auto-enrolled different from backoffice-enrolled?

2016-12-15 14:09 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +    }
These parameters would be shared by both the OrgEnrollmentConfig and the SpaceEnrollmentConfig. So the Config class seemed a better place to house and reuse them. Or do we need a new class for this, if Config is only for env variables.

2016-12-15 14:11 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +public class EnrolledOrganizationConfig {
OrgEnrollmentConfig or SpaceEnrollmentConfig kind of sound similar to the SpaceEnrollerConfig that we already have. But I'm fine with these names too.

2016-12-15 14:12 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +    private String organizationId;
Agreed. I'll rename this to orgGuid then.

2016-12-15 14:14 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +    private Pattern excludeFromAutoEnrollment;
Good point. I think the variable should speak for itself. I'll rename it to excludeSpacesFromAutoEnrollment and create a separate story for excluding apps too.

2016-12-15 14:18 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +
Yes. Story here https://www.pivotaltracker.com/story/show/136184049

2016-12-15 15:46 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +            backoffice_enrolled, backoffice_opted_out
> How different is auto-enrolled different from backoffice-enrolled?

You're right, the difference is small. Might be useful in a UI to distinguish auto-enrolled orgs from manually opted-in enrollments.
I'm fine with restoring to ``enrolled, backoffice_opted_out`` if this is your preference.

2016-12-15 15:47 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +    }
New class seems better to me then, as to keep a clean config contract for env variables

2016-12-15 15:49 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +public class EnrolledOrganizationConfig {
Thanks, lets shoot for OrgEnrollmentConfig for now and revise later if we find better

2016-12-15 15:50 UTC, gberche-orange commented
thanks @pradyutsarma for the additional comments. Please have a look at commits from https://github.com/orange-cloudfoundry/autosleep/tree/feature_org_config_db_GB_refinements if this can help

2016-12-15 16:32 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +            backoffice_enrolled, backoffice_opted_out
Yep. Let's keep it this way for the time being.

2016-12-15 16:34 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +    }
Ok. I'll introduce an EnrollmentConfig class into the same package. Let me know if you prefer any other name.

2016-12-15 16:35 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/dao/model/EnrolledOrganizationConfig.java
> +public class EnrolledOrganizationConfig {
Ok. I'll update the PR accordingly.

2016-12-17 22:05 UTC, pradyutsarma commented
Detailed unit tests for the model parameters will follow in the next PR along with the REST APIs. Hence, did not include them in this. Also, kept the autoEnrollment parameter as it is instead of defaultAutoEnrollment since it's self explanatory as the default value for 'this' org.

2016-12-18 10:01 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/config/Config.java
> +    }
Just thinking...maybe we should also move the ServiceInstanceParameters interface (and its enum) out of Config into the new EnrollmentConfig for the same reason.
If we agree, I will submit the change with the next PR.

2016-12-31 21:05 UTC, pradyutsarma commented
Closing this PR without merge. Will create another PR including the changes from this and additional REST APIs for org enrollment support.

2016-12-31 21:05 UTC, closed without merging