update cf java client 2.7
Orange-OpenSource/autosleep pull request #279
Opened 2017-05-19 16:43 UTC by gberche-orange

fix #264 

@pradyutsarma can you please have a look and merge if this looks good to you ?

2017-05-23 17:17 UTC, pradyutsarma requested changes
@gberche-orange Have a comment and a question before we can merge this?

2017-05-23 17:17 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +import org.cloudfoundry.client.v2.privatedomains.GetPrivateDomainResponse;
Looks like an unused import since we are still using the deprecated GetDomains API.

2017-05-23 17:17 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +        GetDomainResponse domainResponse = cfClient.domains()
Question: We are still using the deprecated API. Do you think we could use the shared/private domains api to figure out the domain?

2017-05-24 07:20 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +        GetDomainResponse domainResponse = cfClient.domains()
Yes, I started coding calls to public and private domain API into https://github.com/cloudfoundry-community/autosleep/pull/279/commits/7064d8c99682f7c6eb8a231fa554d2c790e119f3#diff-de6409188099e3aca52a4e97bd7af702R359 but this still needs refinement:
- complete unit tests
- consider parallel non blocking calls

so I suggest we handle this into a distinct PR

2017-05-24 07:21 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +import org.cloudfoundry.client.v2.privatedomains.GetPrivateDomainResponse;
Good catch, will clean that up in a new commit.

2017-05-24 08:40 UTC, gberche-orange commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +import org.cloudfoundry.client.v2.privatedomains.GetPrivateDomainResponse;
fixed in https://github.com/cloudfoundry-community/autosleep/pull/279/commits/7c1bf4bf1e8ac1ad93bd65b5648ab010ae3f44e3

2017-05-24 10:29 UTC, pradyutsarma commented on common/src/main/java/org/cloudfoundry/autosleep/access/cloudfoundry/CloudFoundryApi.java
> +        GetDomainResponse domainResponse = cfClient.domains()
Ok. No problem.

2017-05-24 10:29 UTC, merged